# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97a6c0d693cccaaf58efe8210a46932d5c12dcbc29890bfd7635d15afbded8d36ede9c54e5cd3fcf22092ac7e57d280468c5778b519b9425c6ccd5888ff2cee3

test:
  secret_key_base: f4b20261589b4013630c2a5d68dbbc6d0d84e0379762fbdcb41cffbecb1bca37e4009b7c61abe7da43951b3d39e9fcb833796e1912b8d3eb400fad548320ed4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
